"""new field in user model

Revision ID: 075109de4a4f
Revises: 3d7e74b05359
Create Date: 2020-01-03 21:43:51.041177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075109de4a4f'
down_revision = '3d7e74b05359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
