"""empty message

Revision ID: 2b152676233d
Revises: 41bff1b43790
Create Date: 2020-01-01 15:27:51.574075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b152676233d'
down_revision = '41bff1b43790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_about'), 'profile', ['about'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_about'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
